# F24-W4111-03: Introduction to Databases: Homework 2, Part B

## Submission Instructions

__Note to TAs:__ The TAs will post submission instructions on Ed, CourseWorks and GradeScope.

## Environment Setup

### Check Packages and Connections

This section tests your environment for HW1B.

If you successfuly completed HW0, you should not have any problems.

Please make sure you set your MySQL user id and password correctly.

In [1]:
# %pip install pandas
import pandas

In [2]:
import sqlalchemy

In [3]:
import pymysql

In [4]:
import json

In [5]:
%load_ext sql

In [6]:
%sql mysql+pymysql://root:MarcuSisnotacoolguy@localhost

In [7]:
engine = sqlalchemy.create_engine("mysql+pymysql://root:dbuserdbuser@localhost")

### Sample Database

For this homework, we need a more complex database and sample data to adequately write and test complex SQL.

We will use the [Classic Models example database](https://www.mysqltutorial.org/getting-started-with-mysql/mysql-sample-database/) for this homework and subsequent homework assignments. The SQL script for creating the database/schema and loading the data is in the same GitHub directory as this notebook. If you downloaded a zip file to start HW2B, the file is in the directory containing the notebook.

In [8]:
%ls -l *.sql

-rw-rw-r--@ 1 marcuslam  staff  195764 Oct 29  2023 mysqlsampledatabase.sql

You install and create the database and install the code in the same way you set up and installed the sample database associated with the recommended textbook. You performed this task earlier in the semester. The [steps](https://www.mysqltutorial.org/getting-started-with-mysql/how-to-load-sample-database-into-mysql-database-server/) for installing the database using the command line is also on the website for Classic Models.

The following cell will check if you have correctly installed the database.

In [10]:
%%sql

use classicmodels;

with one as (
    select
        *
    from
        orders join orderdetails using(orderNumber)
),
    two as (
        select
            *
        from
            customers join one using(customerNumber)
    ),
    three as (
        select
            *
        from
            two join products using(productCode)
    )
select
    customerNumber,
    customerName,
    orderNumber,
    status,
    quantityOrdered,
    priceEach,
    orderLineNumber,
    productName,
    productVendor
from
    three
where
    customerNumber = 114
order by
    customerNumber, orderNumber, orderLineNumber;

 * mysql+pymysql://root:***@localhost
0 rows affected.
55 rows affected.

[(114, 'Australian Collectors, Co.', 10120, 'Shipped', 35, Decimal('110.45'), 1, '1997 BMW R 1100 S', 'Autoart Studio Design'),
 (114, 'Australian Collectors, Co.', 10120, 'Shipped', 46, Decimal('158.80'), 2, '2003 Harley-Davidson Eagle Drag Bike', 'Red Start Diecast'),
 (114, 'Australian Collectors, Co.', 10120, 'Shipped', 29, Decimal('118.94'), 3, '1996 Moto Guzzi 1100i', 'Highway 66 Mini Classics'),
 (114, 'Australian Collectors, Co.', 10120, 'Shipped', 46, Decimal('57.54'), 4, '1936 Harley Davidson El Knucklehead', 'Welly Diecast Productions'),
 (114, 'Australian Collectors, Co.', 10120, 'Shipped', 34, Decimal('72.36'), 5, '1960 BSA Gold Star DBD34', 'Highway 66 Mini Classics'),
 (114, 'Australian Collectors, Co.', 10120, 'Shipped', 22, Decimal('94.90'), 6, '1997 BMW F650 ST', 'Exoto Designs'),
 (114, 'Australian Collectors, Co.', 10120, 'Shipped', 24, Decimal('106.79'), 7, 'ATA: B757-300', 'Highway 66 Mini Classics'),
 (114, 'Australian Collectors, Co.', 10120, 'Shipped', 29, Decimal('82.79'), 8, 'P-51-D Mustang', 'Gearbox Collectibles'),
 (114, 'Australian Collectors, Co.', 10120, 'Shipped', 29, Decimal('71.73'), 9, '1900s Vintage Tri-Plane', 'Unimax Art Galleries'),
 (114, 'Australian Collectors, Co.', 10120, 'Shipped', 39, Decimal('93.01'), 10, '1928 British Royal Navy Airplane', 'Classic Metal Creations'),
 (114, 'Australian Collectors, Co.', 10120, 'Shipped', 29, Decimal('68.79'), 11, '1928 Ford Phaeton Deluxe', 'Highway 66 Mini Classics'),
 (114, 'Australian Collectors, Co.', 10120, 'Shipped', 49, Decimal('41.46'), 12, '1930 Buick Marquette Phaeton', 'Studio M Art Models'),
 (114, 'Australian Collectors, Co.', 10120, 'Shipped', 47, Decimal('91.34'), 13, 'American Airlines: B767-300', 'Min Lin Diecast'),
 (114, 'Australian Collectors, Co.', 10120, 'Shipped', 43, Decimal('72.00'), 14, 'F/A 18 Hornet 1/72', 'Motor City Art Classics'),
 (114, 'Australian Collectors, Co.', 10120, 'Shipped', 24, Decimal('81.77'), 15, 'America West Airlines B757-200', 'Motor City Art Classics'),
 (114, 'Australian Collectors, Co.', 10125, 'Shipped', 32, Decimal('89.38'), 1, '1937 Lincoln Berline', 'Motor City Art Classics'),
 (114, 'Australian Collectors, Co.', 10125, 'Shipped', 34, Decimal('138.38'), 2, '1928 Mercedes-Benz SSK', 'Gearbox Collectibles'),
 (114, 'Australian Collectors, Co.', 10223, 'Shipped', 37, Decimal('80.39'), 1, '1969 Harley Davidson Ultimate Chopper', 'Min Lin Diecast'),
 (114, 'Australian Collectors, Co.', 10223, 'Shipped', 32, Decimal('104.81'), 2, '1997 BMW R 1100 S', 'Autoart Studio Design'),
 (114, 'Australian Collectors, Co.', 10223, 'Shipped', 49, Decimal('189.79'), 3, '2003 Harley-Davidson Eagle Drag Bike', 'Red Start Diecast'),
 (114, 'Australian Collectors, Co.', 10223, 'Shipped', 47, Decimal('110.61'), 4, '1996 Moto Guzzi 1100i', 'Highway 66 Mini Classics'),
 (114, 'Australian Collectors, Co.', 10223, 'Shipped', 28, Decimal('58.75'), 5, '1936 Harley Davidson El Knucklehead', 'Welly Diecast Productions'),
 (114, 'Australian Collectors, Co.', 10223, 'Shipped', 38, Decimal('60.94'), 6, '1960 BSA Gold Star DBD34', 'Highway 66 Mini Classics'),
 (114, 'Australian Collectors, Co.', 10223, 'Shipped', 21, Decimal('90.90'), 7, '1997 BMW F650 ST', 'Exoto Designs'),
 (114, 'Australian Collectors, Co.', 10223, 'Shipped', 29, Decimal('113.90'), 8, 'ATA: B757-300', 'Highway 66 Mini Classics'),
 (114, 'Australian Collectors, Co.', 10223, 'Shipped', 47, Decimal('67.58'), 9, 'P-51-D Mustang', 'Gearbox Collectibles'),
 (114, 'Australian Collectors, Co.', 10223, 'Shipped', 23, Decimal('68.10'), 10, '1900s Vintage Tri-Plane', 'Unimax Art Galleries'),
 (114, 'Australian Collectors, Co.', 10223, 'Shipped', 34, Decimal('87.54'), 11, '1928 British Royal Navy Airplane', 'Classic Metal Creations'),
 (114, 'Australian Collectors, Co.', 10223, 'Shipped', 20, Decimal('66.73'), 12, '1928 Ford Phaeton Deluxe', 'Highway 66 Mini Classics'),
 (114, 'Australian Collectors, Co.', 10223, 'Shipped', 41, Decimal('41.02'), 13, '1930 Buick Marquette Phaeton', 'Studio M Art Models'),
 (114, 'Australian Collectors, Co.', 10223, 'Shipped', 25, Decimal('84.03'), 14, 'American Airlines: B767-300', 'Min Lin Diecast'),
 (114, 'Australian Collectors, Co.', 10223, 'Shipped', 26, Decimal('79.20'), 15, 'F/A 18 Hornet 1/72', 'Motor City Art Classics'),
 (114, 'Australian Collectors, Co.', 10342, 'Shipped', 55, Decimal('63.14'), 1, '1948 Porsche 356-A Roadster', 'Gearbox Collectibles'),
 (114, 'Australian Collectors, Co.', 10342, 'Shipped', 40, Decimal('118.89'), 2, '1993 Mazda RX-7', 'Highway 66 Mini Classics'),
 (114, 'Australian Collectors, Co.', 10342, 'Shipped', 22, Decimal('115.22'), 3, '1995 Honda Civic', 'Min Lin Diecast'),
 (114, 'Australian Collectors, Co.', 10342, 'Shipped', 30, Decimal('167.65'), 4, '1992 Ferrari 360 Spider red', 'Unimax Art Galleries'),
 (114, 'Australian Collectors, Co.', 10342, 'Shipped', 25, Decimal('76.39'), 5, '1969 Dodge Super Bee', 'Min Lin Diecast'),
 (114, 'Australian Collectors, Co.', 10342, 'Shipped', 42, Decimal('112.34'), 6, '1956 Porsche 356A Coupe', 'Classic Metal Creations'),
 (114, 'Australian Collectors, Co.', 10342, 'Shipped', 55, Decimal('136.70'), 7, '1976 Ford Gran Torino', 'Gearbox Collectibles'),
 (114, 'Australian Collectors, Co.', 10342, 'Shipped', 26, Decimal('57.82'), 8, '1957 Vespa GS150', 'Studio M Art Models'),
 (114, 'Australian Collectors, Co.', 10342, 'Shipped', 39, Decimal('30.59'), 9, '1982 Lamborghini Diablo', 'Second Gear Diecast'),
 (114, 'Australian Collectors, Co.', 10342, 'Shipped', 48, Decimal('60.01'), 10, '1971 Alpine Renault 1600s', 'Welly Diecast Productions'),
 (114, 'Australian Collectors, Co.', 10342, 'Shipped', 38, Decimal('124.99'), 11, '1957 Corvette Convertible', 'Classic Metal Creations'),
 (114, 'Australian Collectors, Co.', 10347, 'Shipped', 30, Decimal('188.58'), 1, '1952 Alpine Renault 1300', 'Classic Metal Creations'),
 (114, 'Australian Collectors, Co.', 10347, 'Shipped', 27, Decimal('132.97'), 2, '1962 LanciaA Delta 16V', 'Second Gear Diecast'),
 (114, 'Australian Collectors, Co.', 10347, 'Shipped', 29, Decimal('132.57'), 3, '1958 Setra Bus', 'Welly Diecast Productions'),
 (114, 'Australian Collectors, Co.', 10347, 'Shipped', 45, Decimal('115.03'), 4, '1940s Ford truck', 'Motor City Art Classics'),
 (114, 'Australian Collectors, Co.', 10347, 'Shipped', 42, Decimal('113.17'), 5, '1940 Ford Pickup Truck', 'Studio M Art Models'),
 (114, 'Australian Collectors, Co.', 10347, 'Shipped', 21, Decimal('136.69'), 6, '1928 Mercedes-Benz SSK', 'Gearbox Collectibles'),
 (114, 'Australian Collectors, Co.', 10347, 'Shipped', 21, Decimal('46.36'), 7, '1936 Mercedes-Benz 500K Special Roadster', 'Studio M Art Models'),
 (114, 'Australian Collectors, Co.', 10347, 'Shipped', 50, Decimal('51.05'), 8, '1926 Ford Fire Engine', 'Carousel DieCast Legends'),
 (114, 'Australian Collectors, Co.', 10347, 'Shipped', 48, Decimal('84.09'), 9, '1913 Ford Model T Speedster', 'Carousel DieCast Legends'),
 (114, 'Australian Collectors, Co.', 10347, 'Shipped', 34, Decimal('60.59'), 10, '1934 Ford V8 Coupe', 'Min Lin Diecast'),
 (114, 'Australian Collectors, Co.', 10347, 'Shipped', 45, Decimal('95.30'), 11, '18th Century Vintage Horse Carriage', 'Red Start Diecast'),
 (114, 'Australian Collectors, Co.', 10347, 'Shipped', 26, Decimal('84.33'), 12, '1917 Maxwell Touring Car', 'Exoto Designs')]

## Entity Relationship Modeling

### Create Entity Relationship Model

The ability to take a high-level description of a required database and produce an ER-diagram is one of the most fundamental skills needed for using databases. Consider the following scenario for creating a data model for the Harry Potter series of books.

The data model has the following entity types:
1. ```Character``` has the properties:
    - ```last_name```
    - ```first_name```
    - ```description```
2. ```Book``` has the properties:
    - ```title```
    - ```volume_number``` is the ordinal number of the book in the overall series. For example, [Harry Potter and the Goblet of Fire](https://reedsy.com/discovery/blog/harry-potter-books-in-order) has ```volume_number``` 4.
    - ```publication_year```
3. ```Chapter``` has the properties:
    - ```volume_number```
    - ```chapter_number```
    - ```chapter_title```
    - ```chapter_summary```
4. ```Event``` has the following properties:
    - ```event_type``` is a value from a list of possible event types. The data model should support adding new allowed values for ```event_type``` without requiring changing the data model/schema.
    - ```event_description```

This is where things get tricky. People think of an ```Event``` having a form like:


1. Event: Harry Receives His Hogwarts Letter
- **Type:** Milestone
- **Description:** After multiple failed attempts to deliver a letter to Harry, Hagrid personally delivers his acceptance letter to Hogwarts.
- **Participants:** Harry Potter, Hagrid, Dursley Family
- **Book:** *Harry Potter and the Philosopher's Stone*
- **Chapter:** Chapter 4: "The Keeper of the Keys"

2. Event: Sorting Hat Ceremony
- **Type:** Ceremony
- **Description:** Harry and his classmates are sorted into their respective houses. Harry is placed in Gryffindor despite the Sorting Hat considering Slytherin.
- **Participants:** Harry Potter, Ron Weasley, Hermione Granger, Draco Malfoy, Sorting Hat
- **Book:** *Harry Potter and the Philosopher's Stone*
- **Chapter:** Chapter 7: "The Sorting Hat"

3. Event: Battle of the Department of Mysteries
- **Type:** Battle
- **Description:** Harry and his friends fight Death Eaters at the Ministry of Magic. Sirius Black is killed by Bellatrix Lestrange.
- **Participants:** Harry Potter, Hermione Granger, Ron Weasley, Neville Longbottom, Luna Lovegood, Ginny Weasley, Death Eaters, Order of the Phoenix
- **Book:** *Harry Potter and the Order of the Phoenix*
- **Chapter:** Chapter 35: "Beyond the Veil"

4. Event: Dumbledore's Death
- **Type:** Tragedy
- **Description:** Severus Snape kills Albus Dumbledore at the top of the Astronomy Tower, as part of a prearranged plan.
- **Participants:** Albus Dumbledore, Severus Snape, Draco Malfoy, Death Eaters
- **Book:** *Harry Potter and the Half-Blood Prince*
- **Chapter:** Chapter 27: "The Lightning-Struck Tower"

5. Event: Harry's Final Duel with Voldemort
- **Type:** Battle
- **Description:** Harry confronts Voldemort in the Great Hall and finally defeats him, bringing an end to the Dark Lord's reign.
- **Participants:** Harry Potter, Lord Voldemort
- **Book:** *Harry Potter and the Deathly Hallows*
- **Chapter:** Chapter 36: "The Flaw in the Plan"

You must define and diagram an ER model using Crow's Foot notation that enables representing the information in a relational/SQL database. This should include defining:
- Primary keys
- Foreign keys
- Relationships necessary to represent and store the data.

To accomplish the task, you _may_ need to create additional entity types, attributes, etc.

In the cell below, please document any assumptions/design decisions you make and include the ER diagram.

__Answer:__

- Assumptions/design decisions: See annotations in the ER diagram.


<img src='ER_hw2b.png'>

### Implement ER Diagram

The diagram below is a simple ER Model using specialization to model companies with which a corporation may do business. You must create a database with the name ```w4111_hw2_<uni>```, replacing ```<uni>``` with your UNI.

Your implementation must use the _3 Table Solution_ to modeling specialization.

You need to create the necessary primary keys, foreign keys, views, etc. A query on the table/view ```Company``` must include a column indicating whether the ```Company``` is a ```Supplier``` or a ```Customer.```

| <img src="./er_to_sql_data_model.jpg"> |
| :---: |
| ER to SQL Data Model |

In [18]:
%%sql

CREATE DATABASE IF NOT EXISTS w4111_hw2_sml2286;

USE w4111_hw2_sml2286;

drop table if exists Supplier;
drop table if exists Customer;
drop table if exists Company;

CREATE TABLE Company (
    ID CHAR(12) PRIMARY KEY,
    name VARCHAR(255),
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP /* https://dev.mysql.com/doc/refman/8.4/en/timestamp-initialization.html */
);

CREATE TABLE Supplier(
    supplier_ID CHAR(12) PRIMARY KEY,
    rating INT CHECK (rating IN (0, 1, 2, 3, 4, 5)),
    product_name VARCHAR(255),
    company_type CHAR(8) CHECK (company_type IN ("Supplier", "Customer")),
    FOREIGN KEY (supplier_ID) REFERENCES Company(ID)
);

CREATE TABLE Customer(
    customer_ID CHAR(12) PRIMARY KEY,
    credit_limit INT unsigned,
    credit_rating VARCHAR(10) CHECK (credit_rating IN ('Excellent', 'Good', 'Fair', 'Poor', 'Terrible')),
    company_type CHAR(8) CHECK (company_type IN ("Supplier", "Customer")),
    FOREIGN KEY (customer_ID) REFERENCES Company(ID)
);

/* Trigger when the new created_data is not equal to hte new created_date so that it can't be changed! */
CREATE TRIGGER fix_created_date
BEFORE UPDATE ON Company
FOR EACH ROW
BEGIN
  IF NEW.created_date <> OLD.created_date THEN
    SET NEW.created_date = OLD.created_date;
  END IF;
END;

 * mysql+pymysql://root:***@localhost
1 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.
0 rows affected.

[]

## Relational Algebra

You will use the Relax calulator and the schema associated with the text book for this question.

https://dbis-uibk.github.io/relax/calc/gist/4f7866c17624ca9dfa85ed2482078be8/relax-silberschatz-english.txt/0

Write a relational algebra expression that produces a relation of the form

```(student_id, student_name, student_dept, advisor_id, advisor_name, advisor_dept)```

All students must have a row in the result, event if the student does not have an advisor. All instructors must appear in the result even if the instructor does not advise an students.

Follow the format you used for the previous homework, i.e. paste the text of your expression in the markdown cell below and include the execution result for your expression. You only need to include the first page of results if there is more than one page of results.

```
π student_ID←student.ID, student_name←student.name, student_dept←student.dept_name, advisor_id←advisor.i_id, advisor_name←instructor.name, advisor_dept←instructor.dept_name (student ⟗ student.ID = advisor.s_id (advisor ⟖ advisor.i_id = instructor.ID instructor))
```

<hr>
Execute your query on the Relax calculator and show an image of the first page of your result below.
<hr>
<img src="RA.png">

## SQL

Use the Classic Models database for these questions.

Write a SQL statement that produces a table of the form

```(country, productCode, productName, no_of_customers, number_of_orders)```

Where
- ```country``` is the ```country``` from the ```customers``` table.
- ```product_code``` and ```product_name``` has the obvious meaning.
- ```no_of_customers``` is the distinct number of customers that ordered the product.
- ```number_of_orders``` is the number of orders that contained an ```orderdetails``` with the ```product_code.```

The result should show 0 for ```number_of_customers``` and ```number_of_orders``` when there have been no orders for a product by a customer in the country.

- From the last specification, we should include all customers even though they have no matching tuple in orders. Left join. 
- This would make some tuples have orders attributes being null. We still want to join these with orderdetails, so we need another left join. 
- At this point, our table includes info on all customers, and if there is a match, their order and orderdetails. We finally join this with our products table. Right join, since we want to keep all tuples of products that have no orders. 
- Group by product_code --> aggregate the buyers of each product
- Group by country of each customer --> aggregate by buyers of a specific product from each country
- count distinct customers!

In [39]:
%%sql
use classicmodels;

SELECT 
    customers.country, 
    products.productCode, 
    products.productName, 
    count(DISTINCT customers.customerNumber) as no_of_customers,
    IFNULL(SUM(orderdetails.quantityOrdered), 0) AS number_of_orders /* https://www.w3schools.com/sql/func_sqlserver_isnull.asp*/
    
FROM 
    customers LEFT JOIN orders on customers.customerNumber = orders.customerNumber
    LEFT JOIN orderdetails on orders.orderNumber = orderdetails.orderNumber
    RIGHT JOIN products ON orderdetails.productCode = products.productCode
GROUP BY country, productCode;

 * mysql+pymysql://root:***@localhost
0 rows affected.
1217 rows affected.

[(None, 'S18_3233', '1985 Toyota Supra', 0, Decimal('0')),
 ('Australia', 'S10_1678', '1969 Harley Davidson Ultimate Chopper', 2, Decimal('57')),
 ('Australia', 'S10_1949', '1952 Alpine Renault 1300', 4, Decimal('109')),
 ('Australia', 'S10_2016', '1996 Moto Guzzi 1100i', 3, Decimal('141')),
 ('Australia', 'S10_4698', '2003 Harley-Davidson Eagle Drag Bike', 2, Decimal('117')),
 ('Australia', 'S10_4962', '1962 LanciaA Delta 16V', 3, Decimal('131')),
 ('Australia', 'S12_1099', '1968 Ford Mustang', 1, Decimal('30')),
 ('Australia', 'S12_1666', '1958 Setra Bus', 4, Decimal('188')),
 ('Australia', 'S12_2823', '2002 Suzuki XREO', 1, Decimal('35')),
 ('Australia', 'S12_3990', '1970 Plymouth Hemi Cuda', 1, Decimal('36')),
 ('Australia', 'S18_1097', '1940 Ford Pickup Truck', 4, Decimal('189')),
 ('Australia', 'S18_1129', '1993 Mazda RX-7', 2, Decimal('63')),
 ('Australia', 'S18_1342', '1937 Lincoln Berline', 4, Decimal('126')),
 ('Australia', 'S18_1367', '1936 Mercedes-Benz 500K Special Roadster', 4, Decimal('158')),
 ('Australia', 'S18_1589', '1965 Aston Martin DB5', 1, Decimal('47')),
 ('Australia', 'S18_1749', '1917 Grand Touring Sedan', 2, Decimal('58')),
 ('Australia', 'S18_1889', '1948 Porsche 356-A Roadster', 1, Decimal('55')),
 ('Australia', 'S18_1984', '1995 Honda Civic', 2, Decimal('47')),
 ('Australia', 'S18_2248', '1911 Ford Town Car', 2, Decimal('78')),
 ('Australia', 'S18_2319', '1964 Mercedes Tour Bus', 1, Decimal('22')),
 ('Australia', 'S18_2325', '1932 Model A Ford J-Coupe', 2, Decimal('89')),
 ('Australia', 'S18_2432', '1926 Ford Fire Engine', 2, Decimal('116')),
 ('Australia', 'S18_2581', 'P-51-D Mustang', 2, Decimal('118')),
 ('Australia', 'S18_2625', '1936 Harley Davidson El Knucklehead', 2, Decimal('96')),
 ('Australia', 'S18_2795', '1928 Mercedes-Benz SSK', 3, Decimal('118')),
 ('Australia', 'S18_2870', '1999 Indy 500 Monte Carlo SS', 1, Decimal('27')),
 ('Australia', 'S18_2949', '1913 Ford Model T Speedster', 5, Decimal('231')),
 ('Australia', 'S18_2957', '1934 Ford V8 Coupe', 3, Decimal('78')),
 ('Australia', 'S18_3136', '18th Century Vintage Horse Carriage', 3, Decimal('126')),
 ('Australia', 'S18_3232', '1992 Ferrari 360 Spider red', 2, Decimal('89')),
 ('Australia', 'S18_3278', '1969 Dodge Super Bee', 3, Decimal('102')),
 ('Australia', 'S18_3320', '1917 Maxwell Touring Car', 3, Decimal('88')),
 ('Australia', 'S18_3482', '1976 Ford Gran Torino', 3, Decimal('140')),
 ('Australia', 'S18_3685', '1948 Porsche Type 356 Roadster', 1, Decimal('28')),
 ('Australia', 'S18_3782', '1957 Vespa GS150', 2, Decimal('64')),
 ('Australia', 'S18_3856', '1941 Chevrolet Special Deluxe Cabriolet', 1, Decimal('51')),
 ('Australia', 'S18_4027', '1970 Triumph Spitfire', 1, Decimal('35')),
 ('Australia', 'S18_4409', '1932 Alfa Romeo 8C2300 Spider Sport', 3, Decimal('124')),
 ('Australia', 'S18_4600', '1940s Ford truck', 3, Decimal('112')),
 ('Australia', 'S18_4668', '1939 Cadillac Limousine', 3, Decimal('113')),
 ('Australia', 'S18_4721', '1957 Corvette Convertible', 2, Decimal('71')),
 ('Australia', 'S18_4933', '1957 Ford Thunderbird', 3, Decimal('90')),
 ('Australia', 'S24_1046', '1970 Chevy Chevelle SS 454', 2, Decimal('85')),
 ('Australia', 'S24_1444', '1970 Dodge Coronet', 1, Decimal('25')),
 ('Australia', 'S24_1578', '1997 BMW R 1100 S', 2, Decimal('105')),
 ('Australia', 'S24_1628', '1966 Shelby Cobra 427 S/C', 2, Decimal('84')),
 ('Australia', 'S24_1785', '1928 British Royal Navy Airplane', 2, Decimal('119')),
 ('Australia', 'S24_1937', '1939 Chevrolet Deluxe Coupe', 3, Decimal('104')),
 ('Australia', 'S24_2000', '1960 BSA Gold Star DBD34', 1, Decimal('72')),
 ('Australia', 'S24_2022', '1938 Cadillac V-16 Presidential Limousine', 2, Decimal('44')),
 ('Australia', 'S24_2360', '1982 Ducati 900 Monster', 1, Decimal('38')),
 ('Australia', 'S24_2766', '1949 Jaguar XK 120', 2, Decimal('60')),
 ('Australia', 'S24_2841', '1900s Vintage Bi-Plane', 1, Decimal('21')),
 ('Australia', 'S24_2887', '1952 Citroen-15CV', 2, Decimal('89')),
 ('Australia', 'S24_2972', '1982 Lamborghini Diablo', 1, Decimal('39')),
 ('Australia', 'S24_3191', '1969 Chevrolet Camaro Z28', 2, Decimal('66')),
 ('Australia', 'S24_3371', '1971 Alpine Renault 1600s', 2, Decimal('82')),
 ('Australia', 'S24_3420', '1937 Horch 930V Limousine', 2, Decimal('52')),
 ('Australia', 'S24_3432', '2002 Chevy Corvette', 2, Decimal('53')),
 ('Australia', 'S24_3856', '1956 Porsche 356A Coupe', 1, Decimal('42')),
 ('Australia', 'S24_3949', 'Corsair F4U ( Bird Cage)', 1, Decimal('26')),
 ('Australia', 'S24_3969', '1936 Mercedes Benz 500k Roadster', 2, Decimal('37')),
 ('Australia', 'S24_4048', '1992 Porsche Cayenne Turbo Silver', 1, Decimal('23')),
 ('Australia', 'S24_4258', '1936 Chrysler Airflow', 2, Decimal('49')),
 ('Australia', 'S24_4278', '1900s Vintage Tri-Plane', 2, Decimal('77')),
 ('Australia', 'S24_4620', '1961 Chevrolet Impala', 1, Decimal('24')),
 ('Australia', 'S32_1268', '1980’s GM Manhattan Express', 1, Decimal('32')),
 ('Australia', 'S32_1374', '1997 BMW F650 ST', 1, Decimal('43')),
 ('Australia', 'S32_2206', '1982 Ducati 996 R', 1, Decimal('26')),
 ('Australia', 'S32_3207', "1950's Chicago Surface Lines Streetcar", 1, Decimal('33')),
 ('Australia', 'S32_3522', '1996 Peterbilt 379 Stake Bed with Outrigger', 2, Decimal('46')),
 ('Australia', 'S32_4289', '1928 Ford Phaeton Deluxe', 2, Decimal('98')),
 ('Australia', 'S32_4485', '1974 Ducati 350 Mk3 Desmo', 1, Decimal('34')),
 ('Australia', 'S50_1341', '1930 Buick Marquette Phaeton', 2, Decimal('123')),
 ('Australia', 'S50_4713', '2002 Yamaha YZR M1', 1, Decimal('48')),
 ('Australia', 'S700_1691', 'American Airlines: B767-300', 2, Decimal('92')),
 ('Australia', 'S700_2047', 'HMS Bounty', 2, Decimal('56')),
 ('Australia', 'S700_2466', 'America West Airlines B757-200', 2, Decimal('50')),
 ('Australia', 'S700_2824', '1982 Camaro Z28', 1, Decimal('46')),
 ('Australia', 'S700_2834', 'ATA: B757-300', 2, Decimal('97')),
 ('Australia', 'S700_3167', 'F/A 18 Hornet 1/72', 2, Decimal('113')),
 ('Australia', 'S700_4002', 'American Airlines: MD-11S', 1, Decimal('35')),
 ('Australia', 'S72_1253', 'Boeing X-32A JSF', 2, Decimal('65')),
 ('Austria', 'S10_1678', '1969 Harley Davidson Ultimate Chopper', 1, Decimal('41')),
 ('Austria', 'S10_4757', '1972 Alfa Romeo GTA', 1, Decimal('46')),
 ('Austria', 'S10_4962', '1962 LanciaA Delta 16V', 1, Decimal('21')),
 ('Austria', 'S12_1099', '1968 Ford Mustang', 1, Decimal('57')),
 ('Austria', 'S12_1666', '1958 Setra Bus', 1, Decimal('49')),
 ('Austria', 'S12_2823', '2002 Suzuki XREO', 1, Decimal('55')),
 ('Austria', 'S12_3380', '1968 Dodge Charger', 2, Decimal('101')),
 ('Austria', 'S12_3990', '1970 Plymouth Hemi Cuda', 1, Decimal('70')),
 ('Austria', 'S12_4675', '1969 Dodge Charger', 2, Decimal('128')),
 ('Austria', 'S18_1097', '1940 Ford Pickup Truck', 1, Decimal('36')),
 ('Austria', 'S18_1129', '1993 Mazda RX-7', 1, Decimal('38')),
 ('Austria', 'S18_1589', '1965 Aston Martin DB5', 1, Decimal('37')),
 ('Austria', 'S18_1662', '1980s Black Hawk Helicopter', 1, Decimal('43')),
 ('Austria', 'S18_1889', '1948 Porsche 356-A Roadster', 2, Decimal('59')),
 ('Austria', 'S18_1984', '1995 Honda Civic', 1, Decimal('34')),
 ('Austria', 'S18_2870', '1999 Indy 500 Monte Carlo SS', 1, Decimal('55')),
 ('Austria', 'S18_2957', '1934 Ford V8 Coupe', 2, Decimal('69')),
 ('Austria', 'S18_3029', '1999 Yamaha Speed Boat', 1, Decimal('21')),
 ('Austria', 'S18_3136', '18th Century Vintage Horse Carriage', 1, Decimal('29')),
 ('Austria', 'S18_3232', '1992 Ferrari 360 Spider red', 1, Decimal('35')),
 ('Austria', 'S18_3320', '1917 Maxwell Touring Car', 1, Decimal('36')),
 ('Austria', 'S18_3685', '1948 Porsche Type 356 Roadster', 1, Decimal('43')),
 ('Austria', 'S18_3856', '1941 Chevrolet Special Deluxe Cabriolet', 1, Decimal('27')),
 ('Austria', 'S18_4600', '1940s Ford truck', 1, Decimal('45')),
 ('Austria', 'S18_4668', '1939 Cadillac Limousine', 1, Decimal('25')),
 ('Austria', 'S24_2360', '1982 Ducati 900 Monster', 1, Decimal('32')),
 ('Austria', 'S24_2841', '1900s Vintage Bi-Plane', 1, Decimal('41')),
 ('Austria', 'S24_2972', '1982 Lamborghini Diablo', 1, Decimal('15')),
 ('Austria', 'S24_3151', '1912 Ford Model T Delivery Wagon', 1, Decimal('35')),
 ('Austria', 'S24_3371', '1971 Alpine Renault 1600s', 1, Decimal('55')),
 ('Austria', 'S24_3420', '1937 Horch 930V Limousine', 1, Decimal('20')),
 ('Austria', 'S24_3816', '1940 Ford Delivery Sedan', 1, Decimal('35')),
 ('Austria', 'S24_3856', '1956 Porsche 356A Coupe', 2, Decimal('104')),
 ('Austria', 'S24_3949', 'Corsair F4U ( Bird Cage)', 1, Decimal('28')),
 ('Austria', 'S24_4258', '1936 Chrysler Airflow', 1, Decimal('48')),
 ('Austria', 'S32_1268', '1980’s GM Manhattan Express', 1, Decimal('24')),
 ('Austria', 'S32_3522', '1996 Peterbilt 379 Stake Bed with Outrigger', 1, Decimal('49')),
 ('Austria', 'S32_4485', '1974 Ducati 350 Mk3 Desmo', 1, Decimal('31')),
 ('Austria', 'S50_4713', '2002 Yamaha YZR M1', 1, Decimal('38')),
 ('Austria', 'S700_1138', 'The Schooner Bluenose', 1, Decimal('25')),
 ('Austria', 'S700_2047', 'HMS Bounty', 1, Decimal('29')),
 ('Austria', 'S700_2610', 'The USS Constitution Ship', 1, Decimal('38')),
 ('Austria', 'S700_2824', '1982 Camaro Z28', 1, Decimal('39')),
 ('Austria', 'S700_3167', 'F/A 18 Hornet 1/72', 1, Decimal('34')),
 ('Austria', 'S700_4002', 'American Airlines: MD-11S', 1, Decimal('26')),
 ('Austria', 'S72_1253', 'Boeing X-32A JSF', 1, Decimal('28')),
 ('Belgium', 'S10_4757', '1972 Alfa Romeo GTA', 1, Decimal('30')),
 ('Belgium', 'S18_1662', '1980s Black Hawk Helicopter', 1, Decimal('41')),
 ('Belgium', 'S18_1984', '1995 Honda Civic', 1, Decimal('34')),
 ('Belgium', 'S18_2870', '1999 Indy 500 Monte Carlo SS', 1, Decimal('49')),
 ('Belgium', 'S18_2949', '1913 Ford Model T Speedster', 1, Decimal('10')),
 ('Belgium', 'S18_2957', '1934 Ford V8 Coupe', 1, Decimal('31')),
 ('Belgium', 'S18_3029', '1999 Yamaha Speed Boat', 2, Decimal('62')),
 ('Belgium', 'S18_3136', '18th Century Vintage Horse Carriage', 1, Decimal('21')),
 ('Belgium', 'S18_3140', '1903 Ford Model A', 1, Decimal('73')),
 ('Belgium', 'S18_3232', '1992 Ferrari 360 Spider red', 1, Decimal('34')),
 ('Belgium', 'S18_3259', 'Collectable Wooden Train', 1, Decimal('70')),
 ('Belgium', 'S18_3320', '1917 Maxwell Touring Car', 1, Decimal('21')),
 ('Belgium', 'S18_3856', '1941 Chevrolet Special Deluxe Cabriolet', 2, Decimal('95')),
 ('Belgium', 'S18_4522', '1904 Buick Runabout', 1, Decimal('72')),
 ('Belgium', 'S24_2011', '18th century schooner', 1, Decimal('71')),
 ('Belgium', 'S24_3151', '1912 Ford Model T Delivery Wagon', 1, Decimal('27')),
 ('Belgium', 'S24_3816', '1940 Ford Delivery Sedan', 1, Decimal('48')),
 ('Belgium', 'S24_4258', '1936 Chrysler Airflow', 1, Decimal('28')),
 ('Belgium', 'S32_3207', "1950's Chicago Surface Lines Streetcar", 1, Decimal('27')),
 ('Belgium', 'S32_4289', '1928 Ford Phaeton Deluxe', 1, Decimal('20')),
 ('Belgium', 'S700_1138', 'The Schooner Bluenose', 1, Decimal('21')),
 ('Belgium', 'S700_1938', 'The Mayflower', 1, Decimal('44')),
 ('Belgium', 'S700_2610', 'The USS Constitution Ship', 1, Decimal('42')),
 ('Belgium', 'S700_3505', 'The Titanic', 1, Decimal('40')),
 ('Belgium', 'S700_3962', 'The Queen Mary', 1, Decimal('26')),
 ('Belgium', 'S72_3212', 'Pont Yacht', 1, Decimal('37')),
 ('Canada', 'S10_1949', '1952 Alpine Renault 1300', 2, Decimal('70')),
 ('Canada', 'S10_4757', '1972 Alfa Romeo GTA', 2, Decimal('52')),
 ('Canada', 'S10_4962', '1962 LanciaA Delta 16V', 2, Decimal('67')),
 ('Canada', 'S12_1666', '1958 Setra Bus', 2, Decimal('89')),
 ('Canada', 'S18_1097', '1940 Ford Pickup Truck', 2, Decimal('61')),
 ('Canada', 'S18_1129', '1993 Mazda RX-7', 1, Decimal('35')),
 ('Canada', 'S18_1984', '1995 Honda Civic', 1, Decimal('35')),
 ('Canada', 'S18_2319', '1964 Mercedes Tour Bus', 1, Decimal('29')),
 ('Canada', 'S18_2432', '1926 Ford Fire Engine', 1, Decimal('34')),
 ('Canada', 'S18_2581', 'P-51-D Mustang', 1, Decimal('24')),
 ('Canada', 'S18_2949', '1913 Ford Model T Speedster', 1, Decimal('37')),
 ('Canada', 'S18_2957', '1934 Ford V8 Coupe', 1, Decimal('28')),
 ('Canada', 'S18_3029', '1999 Yamaha Speed Boat', 1, Decimal('21')),
 ('Canada', 'S18_3136', '18th Century Vintage Horse Carriage', 1, Decimal('30')),
 ('Canada', 'S18_3232', '1992 Ferrari 360 Spider red', 2, Decimal('64')),
 ('Canada', 'S18_3320', '1917 Maxwell Touring Car', 1, Decimal('28')),
 ('Canada', 'S18_3856', '1941 Chevrolet Special Deluxe Cabriolet', 1, Decimal('46')),
 ('Canada', 'S18_4522', '1904 Buick Runabout', 2, Decimal('54')),
 ('Canada', 'S18_4600', '1940s Ford truck', 2, Decimal('74')),
 ('Canada', 'S18_4668', '1939 Cadillac Limousine', 2, Decimal('56')),
 ('Canada', 'S24_1785', '1928 British Royal Navy Airplane', 1, Decimal('23')),
 ('Canada', 'S24_2011', '18th century schooner', 2, Decimal('78')),
 ('Canada', 'S24_2300', '1962 Volkswagen Microbus', 1, Decimal('42')),
 ('Canada', 'S24_2972', '1982 Lamborghini Diablo', 1, Decimal('36')),
 ('Canada', 'S24_3151', '1912 Ford Model T Delivery Wagon', 2, Decimal('56')),
 ('Canada', 'S24_3816', '1940 Ford Delivery Sedan', 1, Decimal('33')),
 ('Canada', 'S24_3949', 'Corsair F4U ( Bird Cage)', 1, Decimal('33')),
 ('Canada', 'S24_4258', '1936 Chrysler Airflow', 1, Decimal('33')),
 ('Canada', 'S24_4278', '1900s Vintage Tri-Plane', 1, Decimal('40')),
 ('Canada', 'S32_1268', '1980’s GM Manhattan Express', 2, Decimal('53')),
 ('Canada', 'S32_1374', '1997 BMW F650 ST', 1, Decimal('41')),
 ('Canada', 'S32_2509', '1954 Greyhound Scenicruiser', 1, Decimal('38')),
 ('Canada', 'S32_3522', '1996 Peterbilt 379 Stake Bed with Outrigger', 2, Decimal('97')),
 ('Canada', 'S32_4289', '1928 Ford Phaeton Deluxe', 1, Decimal('34')),
 ('Canada', 'S50_1341', '1930 Buick Marquette Phaeton', 1, Decimal('41')),
 ('Canada', 'S700_1138', 'The Schooner Bluenose', 2, Decimal('79')),
 ('Canada', 'S700_1691', 'American Airlines: B767-300', 1, Decimal('25')),
 ('Canada', 'S700_2047', 'HMS Bounty', 1, Decimal('20')),
 ('Canada', 'S700_2466', 'America West Airlines B757-200', 1, Decimal('38')),
 ('Canada', 'S700_2610', 'The USS Constitution Ship', 2, Decimal('91')),
 ('Canada', 'S700_2824', '1982 Camaro Z28', 2, Decimal('97')),
 ('Canada', 'S700_2834', 'ATA: B757-300', 1, Decimal('25')),
 ('Canada', 'S700_3167', 'F/A 18 Hornet 1/72', 1, Decimal('32')),
 ('Canada', 'S700_3505', 'The Titanic', 2, Decimal('47')),
 ('Canada', 'S700_3962', 'The Queen Mary', 2, Decimal('88')),
 ('Canada', 'S700_4002', 'American Airlines: MD-11S', 1, Decimal('34')),
 ('Canada', 'S72_1253', 'Boeing X-32A JSF', 1, Decimal('43')),
 ('Canada', 'S72_3212', 'Pont Yacht', 2, Decimal('62')),
 ('Denmark', 'S10_4757', '1972 Alfa Romeo GTA', 1, Decimal('50')),
 ('Denmark', 'S12_1099', '1968 Ford Mustang', 1, Decimal('28')),
 ('Denmark', 'S12_1108', '2001 Ferrari Enzo', 2, Decimal('79')),
 ('Denmark', 'S12_3148', '1969 Corvair Monza', 1, Decimal('46')),
 ('Denmark', 'S12_3380', '1968 Dodge Charger', 1, Decimal('29')),
 ('Denmark', 'S12_3891', '1969 Ford Falcon', 2, Decimal('65')),
 ('Denmark', 'S12_3990', '1970 Plymouth Hemi Cuda', 1, Decimal('20')),
 ('Denmark', 'S12_4473', '1957 Chevy Pickup', 1, Decimal('45')),
 ('Denmark', 'S18_1129', '1993 Mazda RX-7', 2, Decimal('89')),
 ('Denmark', 'S18_1342', '1937 Lincoln Berline', 1, Decimal('34')),
 ('Denmark', 'S18_1367', '1936 Mercedes-Benz 500K Special Roadster', 1, Decimal('29')),
 ('Denmark', 'S18_1589', '1965 Aston Martin DB5', 1, Decimal('43')),
 ('Denmark', 'S18_1662', '1980s Black Hawk Helicopter', 1, Decimal('25')),
 ('Denmark', 'S18_1984', '1995 Honda Civic', 2, Decimal('96')),
 ('Denmark', 'S18_2238', '1998 Chrysler Plymouth Prowler', 1, Decimal('42')),
 ('Denmark', 'S18_2581', 'P-51-D Mustang', 1, Decimal('45')),
 ('Denmark', 'S18_2870', '1999 Indy 500 Monte Carlo SS', 1, Decimal('23')),
 ('Denmark', 'S18_3029', '1999 Yamaha Speed Boat', 1, Decimal('25')),
 ('Denmark', 'S18_3140', '1903 Ford Model A', 2, Decimal('42')),
 ('Denmark', 'S18_3259', 'Collectable Wooden Train', 2, Decimal('61')),
 ('Denmark', 'S18_3278', '1969 Dodge Super Bee', 1, Decimal('41')),
 ('Denmark', 'S18_3482', '1976 Ford Gran Torino', 1, Decimal('49')),
 ('Denmark', 'S18_3685', '1948 Porsche Type 356 Roadster', 2, Decimal('101')),
 ('Denmark', 'S18_4027', '1970 Triumph Spitfire', 1, Decimal('29')),
 ('Denmark', 'S18_4522', '1904 Buick Runabout', 1, Decimal('41')),
 ('Denmark', 'S18_4721', '1957 Corvette Convertible', 1, Decimal('44')),
 ('Denmark', 'S18_4933', '1957 Ford Thunderbird', 1, Decimal('25')),
 ('Denmark', 'S24_1046', '1970 Chevy Chevelle SS 454', 1, Decimal('37')),
 ('Denmark', 'S24_1444', '1970 Dodge Coronet', 1, Decimal('44')),
 ('Denmark', 'S24_1628', '1966 Shelby Cobra 427 S/C', 1, Decimal('23')),
 ('Denmark', 'S24_2011', '18th century schooner', 1, Decimal('43')),
 ('Denmark', 'S24_2766', '1949 Jaguar XK 120', 1, Decimal('20')),
 ('Denmark', 'S24_2840', '1958 Chevy Corvette Limited Edition', 1, Decimal('39')),
 ('Denmark', 'S24_2887', '1952 Citroen-15CV', 1, Decimal('25')),
 ('Denmark', 'S24_3151', '1912 Ford Model T Delivery Wagon', 1, Decimal('44')),
 ('Denmark', 'S24_3191', '1969 Chevrolet Camaro Z28', 1, Decimal('20')),
 ('Denmark', 'S24_3371', '1971 Alpine Renault 1600s', 1, Decimal('47')),
 ('Denmark', 'S24_3432', '2002 Chevy Corvette', 1, Decimal('30')),
 ('Denmark', 'S24_3816', '1940 Ford Delivery Sedan', 1, Decimal('50')),
 ('Denmark', 'S24_4048', '1992 Porsche Cayenne Turbo Silver', 1, Decimal('38')),
 ('Denmark', 'S24_4620', '1961 Chevrolet Impala', 1, Decimal('22')),
 ('Denmark', 'S32_3207', "1950's Chicago Surface Lines Streetcar", 1, Decimal('35')),
 ('Denmark', 'S50_1392', 'Diamond T620 Semi-Skirted Tanker', 1, Decimal('28')),
 ('Denmark', 'S50_1514', '1962 City of Detroit Streetcar', 1, Decimal('38')),
 ('Denmark', 'S700_1138', 'The Schooner Bluenose', 1, Decimal('41')),
 ('Denmark', 'S700_1938', 'The Mayflower', 2, Decimal('72')),
 ('Denmark', 'S700_2610', 'The USS Constitution Ship', 1, Decimal('52')),
 ('Denmark', 'S700_3505', 'The Titanic', 1, Decimal('82')),
 ('Denmark', 'S700_3962', 'The Queen Mary', 1, Decimal('59')),
 ('Denmark', 'S72_3212', 'Pont Yacht', 1, Decimal('62')),
 ('Finland', 'S10_1678', '1969 Harley Davidson Ultimate Chopper', 1, Decimal('23')),
 ('Finland', 'S10_4698', '2003 Harley-Davidson Eagle Drag Bike', 1, Decimal('29')),
 ('Finland', 'S10_4757', '1972 Alfa Romeo GTA', 2, Decimal('71')),
 ('Finland', 'S12_1099', '1968 Ford Mustang', 1, Decimal('33')),
 ('Finland', 'S12_1108', '2001 Ferrari Enzo', 1, Decimal('44')),
 ('Finland', 'S12_2823', '2002 Suzuki XREO', 1, Decimal('24')),
 ('Finland', 'S12_3148', '1969 Corvair Monza', 1, Decimal('25')),
 ('Finland', 'S12_3380', '1968 Dodge Charger', 1, Decimal('34')),
 ('Finland', 'S12_3891', '1969 Ford Falcon', 1, Decimal('27')),
 ('Finland', 'S12_3990', '1970 Plymouth Hemi Cuda', 2, Decimal('58')),
 ('Finland', 'S12_4473', '1957 Chevy Pickup', 2, Decimal('45')),
 ('Finland', 'S12_4675', '1969 Dodge Charger', 3, Decimal('117')),
 ('Finland', 'S18_1129', '1993 Mazda RX-7', 1, Decimal('35')),
 ('Finland', 'S18_1662', '1980s Black Hawk Helicopter', 2, Decimal('66')),
 ('Finland', 'S18_1889', '1948 Porsche 356-A Roadster', 3, Decimal('99')),
 ('Finland', 'S18_1984', '1995 Honda Civic', 1, Decimal('36')),
 ('Finland', 'S18_2238', '1998 Chrysler Plymouth Prowler', 2, Decimal('82')),
 ('Finland', 'S18_2319', '1964 Mercedes Tour Bus', 2, Decimal('96')),
 ('Finland', 'S18_2432', '1926 Ford Fire Engine', 1, Decimal('39')),
 ('Finland', 'S18_3029', '1999 Yamaha Speed Boat', 2, Decimal('66')),
 ('Finland', 'S18_3232', '1992 Ferrari 360 Spider red', 3, Decimal('141')),
 ('Finland', 'S18_3278', '1969 Dodge Super Bee', 1, Decimal('46')),
 ('Finland', 'S18_3482', '1976 Ford Gran Torino', 1, Decimal('24')),
 ('Finland', 'S18_3782', '1957 Vespa GS150', 2, Decimal('71')),
 ('Finland', 'S18_3856', '1941 Chevrolet Special Deluxe Cabriolet', 2, Decimal('79')),
 ('Finland', 'S18_4027', '1970 Triumph Spitfire', 1, Decimal('48')),